#!/bin/bash

curl "https://adventofcode.com/2021/day/$1/input" \
  -H "Cookie: session=$AOC;" \
  -H 'Accept: text/html,text/plain' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' > $1.in

