#!/bin/bash

if [ -z ${1+x} ]; then
  d="$(date '+%d' | sed 's/^0//g')"
else
  d=$1
fi

y="20$(pwd | grep -o '[0-9]*')"

curl "https://adventofcode.com/$y/day/$d/input" \
  -H "Cookie: session=$AOC;" \
  -H 'Accept: text/html,text/plain' \
  -H 'Pragma: no-cache' \
  -H 'User-Agent: github.com/lebuenti/aoc by florian@zemke.io' \
  -H 'Cache-Control: no-cache' > $d.in

echo "#"'!'"/usr/bin/env python3" > $d.py
echo >> $d.py

echo 'L = """' >> $d.py
echo '""".strip()' >> $d.py
echo "L = open('$d.in').read()" >> $d.py
echo "ll = L.splitlines()" >> $d.py
echo >> $d.py

echo "good luck with day $d of $y \o/"

open https://adventofcode.com/$y/day/$d
vi $d.py

